---
name: Acme-MetaSyntactic-daleks
version: 1.01
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: EXTERMINATE! EXTERMINATE! EXTERMINATE!
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Acme::MetaSyntactic: 0.99
build_requires:
  Test::More: 0
provides:
  Acme::MetaSyntactic::daleks:
    file: lib/Acme/MetaSyntactic/daleks.pm
    version: 1.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
